#make file - this is a comment section
 
CC=g++  #compiler

all: singleton sdp 
 
singleton:    singleton.o
	$(CC) singleton.cpp -o singleton
 
sdp:    sdp.o
	$(CC) sdp.cpp -o sdp

clean:
	rm *.o singleton sdp
